repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: Run rustfmt
        entry: rustfmt
        language: system
        types: [rust]
        pass_filenames: true
      - id: cargo-sort
        name: Run cargo sort
        entry: cargo sort
        language: system
        files: ^Cargo\.toml$
        pass_filenames: false
      - id: cargo-clippy
        name: Run cargo clippy
        entry: cargo clippy --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false